dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'

addons:
  apt:
    packages:
    - libstdc++6
    - gcc-4.8
    - g++-4.8

cache:
  - pip
  - directories:
      - carball/generated/binaries
      - protobuf-2.6.1/
      - v2.6.1/

# We only build if it is a pr into master or it is a pr and it is not into master
if:
  branch = master OR (type = pull_request AND NOT branch = master)


before_install:
- chmod 777 ./_travis/install-protoc.sh
- "./_travis/install-protoc.sh 2.6.1"
- chmod 777 ./_travis/install-protoc-runtime.sh
- "./_travis/install-protoc-runtime.sh 2.6.1"

install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
- python init.py
- ldd --version

script:
- pytest --cov=./ --ignore=protobuf-2.6.1/
- bash <(curl -s https://codecov.io/bash) -c -F carball

after_success:
- codecov

stages:
  - name: test
  - name: deploy
    if: branch = master AND NOT fork AND type = push
  - name: announcement


jobs:
  include:
    - stage: deploy
      script: echo "move on to deploy"
      after_success: echo "move on to deploy"
      deploy:
      - provider: releases
        api_key:
          secure: IgeO5fZQXWRx0LEOLuilkLTP1Hi15Lv86jAySHsPgR1NNOkst+zDy2awOSJ6kThIhozD4wAqBeIpEaCNoq3516O/AIrZmcaOrZWFZqU9Lb+YqH8AVlz1XjkR/hO1msRG+nQKoDzOGo6DtDb0nu9iJVYcHiTv9yQbe+h97oVWeA3MxRdaxbJWfAiAVD7xmbRG+PENQv/wCu6sHPuDlOfKDun5F6POvgLp+4zcwHn1Q+fq2sh8AvJ5uGofBpvky+171bRtVBxhmhABEECvXUlJig/uvyjG7onwwkZJOQMl75mONm1wuzZBpd+hxrNCdOtDN/2wrRuXJH99itoe1Y71IVNgwXsp1DrewzM3i7Y3ivBooywNoScgnJOu8D/Ip/WOgGOXnU+NN11+/zlq/h0j0wiVIwC34dGOo4EjA1cnWVgih2m9YL7xJ5YglZrw7RmkgxIRzrfRmreUelsH735aASlkyy5357uWdKtbhX9kOBgtxHr2b2TeWnvZIdKMX7aiDHc4fW3L2Ml9tb7nJAZzQ1+7APyO0z05iau7G4ZBVFP0a2HS6GguZpcI3zFk+4zZ00pQEvUI9fdTt+Q9PnFMpu7Y+94DWMEXkTWGjT5l4uopbvaiMWb1GlsTlDNWy8mwDhO6wKtpReqslesQ9+6Mzgxmausw/CokOodxhowJyoE=
        file: README.md
        on:
          repo: SaltieRL/carball
          branch: master
          type: push
          tags: true
        skip_cleanup: true
      - provider: pypi
        skip_cleanup: true
        skip_existing: true
        user: $PYPI_LOGIN
        password: $PYPI_PASSWORD
        on:
          repo: SaltieRL/carball
          branch: master
          type: push
    - stage: announcement
      name: "Announce success"
      python: "3.7"
      before_install: skip
      install: skip
      script: skip
      after_success:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x _travis/send.sh
        - ./_travis/send.sh success $WEBHOOK_URL
